### PR TITLE
add  map with 2 ways

### PR DESCRIPTION
**Pull request by kaka5277**
## Rationale
- This is for testing the git workflow

## Advice for Reviewers & Testing Notes 
- Explain how your change should be reviewed, and where reviewers should direct their attention.
- Explain (where relevant) how your change can be tested.

## Screenshots:
- Add a screenshot or two of your changes, where applicable.

## Task Name
- Issue Title

## Linting Checklist
- [ ] No commented code
- [ ] Code Formatted nicely (Prettier)
- [ ] PR your own code before you assign reviewers

### CODE REVIEW

**Comment by kaka5277** [comment]
Hi Dave,i just added map with both 2 ways in contact page just for try.one is in static way ,with a iframe tag . the other one is with google map api keys.and if using this one in the future,need to create a new key  with some restriction settings for this project.
that's all what i know about adding a map in a page.I need your feedback when you have time ,i really appreciate your  idea,it's a good opportunity to learn about it.
thank you

**Comment by davidtaing** [comment]
For this one, let's go with an iframe since that was what the template was using. Let's remove the Google Map API for now.

Well done in spotting another way to do this. I didn't know you could do that, thanks for teaching me something.

**Comment by kaka5277** [comment]
ok now Dave.i just using iframe one,and already git push.thank you for your advice and review.

**Review by davidtaing — APPROVED** [review]
Well done as always. Merging in.

**Comment by kaka5277** [comment]
Thank you dave


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codesydney/aicta"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 中午11:38
***@***.***&gt;;
抄送:&nbsp;"Jun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [codesydney/aicta] add  map with 2 ways (PR #13)





 
Merged #13 into main.

**Pull request merged**
